version: '3'

services:
  phpc1:
    container_name: phpc1
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  phpc2:
    container_name: phpc2
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  phpc3:
    container_name: phpc3
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  phpc4:
    container_name: phpc4
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  phpc5:
    container_name: phpc5
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  phpc6:
    container_name: phpc6
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  phpc7:
    container_name: phpc7
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  phpc8:
    container_name: phpc8
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  nginx1180:
    container_name: nginx1180
    image: wachira90/nginx:1.18.0
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./conf.d/ssl.conf:/etc/nginx/conf.d/ssl.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    healthcheck:
      interval: 5s
    ports:
      - "7000:80"
      - "4443:443"

networks:
  default:
#    external:
#      name:
#        web_network
