version: '3'

services:
  php1:
    container_name: php1
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  php2:
    container_name: php2
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  php3:
    container_name: php3
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  php4:
    container_name: php4
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  php5:
    container_name: php5
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  php6:
    container_name: php6
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  php7:
    container_name: php7
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  php8:
    container_name: php8
    image: wachira90/php:7.2
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    expose:
      - 9000

  nginx1:
    container_name: nginx1
    image: wachira90/nginx:1.18.0
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      interval: 5s
    ports:
      - "7000:80"
      - "4443:443"

networks:
  default:
#    external:
#      name:
#        web_network
